### ISSUE TITLE
Bean Validation Support

### ISSUE THREAD

**Issue by keilw** [JavaMoney/javamoney-midas#14]
Midas should provide JSR 354 support for Bean Validation adding e.g. constraints like _MonetaryMin_, _MonetaryMax_, etc.

**Comment by otaviojava** [comment]
@keilw what do you think about these annotations?
- https://github.com/JavaMoney/javamoney-midas/blob/master/javaee7/src/main/java/org/javamoney/midas/javaee7/validator/MonetaryAmountMaxValidator.java
- https://github.com/JavaMoney/javamoney-midas/blob/master/javaee7/src/main/java/org/javamoney/midas/javaee7/validator/MonetaryAmountMinValidator.java

**Comment by keilw** [comment]
Sounds good, but as further step, huge bowl with all (EE) JSRs in one place should be modularized, not everyone who uses one will need all of them;-)

**Comment by otaviojava** [comment]
Ok.
About the modularized there is one issue to that.
https://github.com/JavaMoney/javamoney-midas/issues/5
So, I am closing this.

**Comment by keilw** [comment]
This has nothing to do with modularization, BeanValidation is one module of many to be created, so the other task is a BLOCKER for this one, not a duplicate ;-)

**Comment by otaviojava** [comment]
Werner.
There are two stuff different.
- The title says: _"Bean Validation Support"_
- The description says: _"Midas should provide JSR 354 support for Bean Validation adding e.g. constraints like MonetaryMin, MonetaryMax, etc."_

Ok, we have support to do this.

**Comment by keilw** [comment]
Yes and the task shall be open until it's done. GitHub does not have such fine-grained dependencies, but you're open to spin-off detailed tasks for Min, Max, etc. later, still the "epic" if you want is a ticket like this one.

**Comment by keilw** [comment]
Actually Zalando has done that already https://github.com/zalando/money-validation
guess we don't have to reinvent the wheel here ;-)
