### ISSUE TITLE
Use Moneta-BP with Java EE 7

### ISSUE THREAD

**Issue by keilw** [JavaMoney/javamoney-midas#6]
Java EE 7 "may" run with SE 8, but it does not have a mandatory requirement nor any dependency on SE 8 features. Therefore the Java EE 7 modules are supposed to respect that, otherwise they won't be compatible with Java EE 7.

**Comment by keilw** [comment]
A "javaee7" module must not use Moneta, but has to use Moneta-BP.
Either use Moneta-BP or please clone the "javaee7" module by using either a qualifier "jdk8" or another  artifactId. The term "BP" is useless here, you're either "javaee7" compatible or not, using or even offering libraries that only run on Java SE 8 is not Java EE 7 compatible;-)

**Comment by otaviojava** [comment]
I believe in you, but yet, all the library just has 10K bytes and the JVM just will load to memory what will really used.

**Comment by otaviojava** [comment]
Now we are using the Moneta-BP.
Problem fixed.
